# -*- coding: utf-8 -*-
"""load_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9hS2DhkXaFmU6HPgBMYRn6CbwpdeV8d
"""

from pathlib import Path
import requests

path = Path('model_yolo')
path.mkdir(exist_ok=True, parents=True)
assert path.exists()

r_w = requests.get('https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1i3MIq53TGaKrDD_nbRZvzjOP56gt-wm1')
with open('model_yolo/weights.h5', 'wb') as file:
    file.write(r_w.content)

r_j = requests.get('https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1Kl7d_Bks8kXBOmuk_M4Cr-0oY1lZ1ZIU')
with open('model_yolo/model.json', 'wb') as file:
    file.write(r_j.content)

