# -*- coding: utf-8 -*-
"""сamera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cxS5BdJlbYl3vFGLfDEdT1lYOlfszt8h
"""

import cv2
from functions import emotionVideo

if __name__ == '__main__':
    camera = cv2.VideoCapture(2)
    emotionVideo(camera)